spring:
  datasource:
    platform: org.hibernate.dialect.H2Dialect
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db
    username: fdt30
    password: fdt30
  jpa:
    generate-ddl: true
#    properties:
#      javax.persistence.schema-generation.scripts.action: create
#      javax.persistence.schema-generation.scripts.create-target: create.sql
#      javax.persistence.schema-generation.scripts.create-source: metadata

jwt.secret: ${JWT_SECRET}