spring:
  datasource:
    platform: org.hibernate.dialect.H2Dialect
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db
    username: fdt30
    password: fdt30
  jpa:
    generate-ddl: true
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        show-sql: true

#    properties:
#      javax.persistence.schema-generation.scripts.action: create
#      javax.persistence.schema-generation.scripts.create-target: create.sql
#      javax.persistence.schema-generation.scripts.create-source: metadata

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

jwt.secret: ${JWT_SECRET}
